debug: true
# Minimum amount of players that need to be online on one server to start balancing
# new players to the other server (e.g. between lobby_1_8_a & lobby_1_8_b)
# Use -1 to disable that feature
start-balancing: 0
join:
  lobby:
    versions:
      '34': lobby_prot_34 # Lobby for specific protocol version
      '1_8': lobby_1_8_a, lobby_1_8_b # Lobbies for 1.8
      '1_9': lobby_1_9 # Lobby for 1.9
      UNKNOWN: well_we_dont_know # Lobby for an Unknown version (not a fallback if no config for version was found!)
    forge:
      '1_9': forge_lobby_1_9
      '1_8': forge_lobby_1_8_a, forge_lobby_1_8_b
    mods:
      "modname1,modname2": mod_server
#servers:
#  survival:
#    versions:
#      '1_8': survival_1_8
#      '1_10': survival_1_10
#      UNKNOWN: survival_wat
#    forge:
#      '1_9': forge_suvival_1_9
#      '1_8': forge_suvival_1_8_a, forge_suvival_1_8_b